### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by StarDream521** [TartaricAcid/BakaDanmaku#10]
作者你好 你在mcbbs上发帖的下载地址 已经404
可以重发一次吗？

**Comment by bd-dxg** [comment]
附议.  bbs上的地址已经404了

**Comment by kevinluo6188** [comment]
+1

**Comment by kevinluo6188** [comment]
在2020年05月13日 15:32，Mr-Q 写道： 

附议.  bbs上的地址已经404了



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/TartaricAcid/BakaDanmaku/issues/10#issuecomment-627803966",

"url": "https://github.com/TartaricAcid/BakaDanmaku/issues/10#issuecomment-627803966",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by kevinluo6188** [comment]
![D608CABF-6DF8-4AEF-89F1-BC4E35C391CA](https://user-images.githubusercontent.com/36571233/81838000-2524bc00-9578-11ea-9bfc-382071017464.png)
